#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate epic_variables.h with all EPIC ECU variables from variables.json
"""

import json
import sys
from pathlib import Path

# Fix Windows console encoding
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

def generate_header_file(variables_json_path, output_path):
    """Generate C header file with all EPIC variables"""
    
    with open(variables_json_path, 'r', encoding='utf-8') as f:
        variables = json.load(f)
    
    # Filter to only output variables (readable)
    output_vars = [v for v in variables if v.get('source') == 'output']
    
    # Sort by name for easier navigation
    output_vars.sort(key=lambda x: x.get('name', '').lower())
    
    print(f"Processing {len(output_vars)} output variables...")
    
    # Generate header file
    header_content = []
    header_content.append("#ifndef EPIC_VARIABLES_H")
    header_content.append("#define EPIC_VARIABLES_H")
    header_content.append("")
    header_content.append("#include <stdint.h>")
    header_content.append("")
    header_content.append("// EPIC ECU Variable Definitions")
    header_content.append("// Auto-generated from EPIC firmware variables.json")
    header_content.append(f"// Total output variables: {len(output_vars)}")
    header_content.append("// Generated by: generate_epic_variables_header.py")
    header_content.append("")
    header_content.append("// Structure to hold variable metadata")
    header_content.append("typedef struct {")
    header_content.append("    int32_t var_id;      // Variable hash ID")
    header_content.append("    const char* name;    // Human-readable name (for CSV header)")
    header_content.append("} EpicVariable;")
    header_content.append("")
    header_content.append("// =========================================")
    header_content.append("// Variable ID Constants (for direct use)")
    header_content.append("// =========================================")
    header_content.append("")
    
    # Generate #define constants for each variable
    # Group by category for better organization
    common_vars = ['TPSValue', 'RPMValue', 'AFRValue', 'MAPValue', 'oilPressure', 
                   'rawClt', 'rawIat', 'coolantTemperature', 'intakeAirTemperature']
    
    header_content.append("// Common sensor variables (most frequently used)")
    header_content.append("")
    for var in output_vars:
        var_name = var.get('name', '')
        if var_name in common_vars:
            hash_id = var.get('hash')
            # Convert name to C-style constant name
            const_name = f"VAR_ID_{var_name.upper()}"
            header_content.append(f"#define {const_name:<45} {hash_id:>15}  // {var_name}")
    
    header_content.append("")
    header_content.append("// All EPIC ECU output variables")
    header_content.append("")
    for var in output_vars:
        var_name = var.get('name', '')
        hash_id = var.get('hash')
        # Convert name to C-style constant name
        # Replace special characters and make uppercase
        const_name = f"VAR_ID_{var_name.upper().replace('.', '_').replace('-', '_')}"
        if var_name not in common_vars:  # Skip if already added above
            header_content.append(f"#define {const_name:<45} {hash_id:>15}  // {var_name}")
    
    header_content.append("")
    header_content.append("// =========================================")
    header_content.append("// EPIC Variables Array (for logging)")
    header_content.append("// =========================================")
    header_content.append("")
    header_content.append("// NOTE: This array includes ALL output variables by default.")
    header_content.append("// Comment out variables you don't need to reduce memory usage.")
    header_content.append("// The array is sorted alphabetically for easy navigation.")
    header_content.append("")
    header_content.append("static const EpicVariable EPIC_VARIABLES[] = {")
    
    # Add variables to array
    for i, var in enumerate(output_vars):
        var_name = var.get('name', '')
        hash_id = var.get('hash')
        const_name = f"VAR_ID_{var_name.upper().replace('.', '_').replace('-', '_')}"
        comma = "," if i < len(output_vars) - 1 else ""
        header_content.append(f"    {{{const_name}, \"{var_name}\"}}{comma}")
    
    header_content.append("};")
    header_content.append("")
    header_content.append("// Ensure EPIC_VAR_COUNT is properly defined")
    header_content.append("static_assert(sizeof(EPIC_VARIABLES) > 0, \"EPIC_VARIABLES array must not be empty\");")
    header_content.append("")
    header_content.append("#define EPIC_VAR_COUNT (sizeof(EPIC_VARIABLES) / sizeof(EPIC_VARIABLES[0]))")
    header_content.append("")
    header_content.append("#endif // EPIC_VARIABLES_H")
    
    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(header_content))
    
    print(f"Generated {output_path}")
    print(f"  - {len(output_vars)} variable constants defined")
    print(f"  - EPIC_VARIABLES array with {len(output_vars)} entries")
    return len(output_vars)

if __name__ == '__main__':
    # Try project-local file first, then fall back to EPIC firmware location
    epic_vars_path = Path('keyboard_basic1/variables.json')
    if not epic_vars_path.exists():
        epic_vars_path = Path(r'c:\Users\user1\Downloads\epicefi_fw-master\epicefi_fw-master\epic_can_bus\variables.json')
    output_path = Path('keyboard_basic1/epic_variables.h')
    
    if not epic_vars_path.exists():
        print(f"Error: Variables file not found at {epic_vars_path}")
        sys.exit(1)
    
    count = generate_header_file(epic_vars_path, output_path)
    print(f"\nSuccess! Generated epic_variables.h with {count} variables.")

